### ISSUE TITLE
Build Instructions.

### ISSUE THREAD

**Issue by filterfish** [mpetris/catma#122]
I would really like to install Catma locally but I'm really struggling to build it.

I've installed Eclipse (I'm not actually sure this is the right thing to do but I saw a reference to ivyde in the commit log) but I'm still getting lots of unresolved types.

I don't think it needs much but something would be really good.

**Comment by mpetris** [comment]
Hi Richard,

thanks for your interest in CATMA!
So, here are some details for creating your own build:

I use the IvyDE and Vaadin Plugin.
To run CATMA from the IDE I use http://eclipse-jetty.github.io/
You need the CATMA core as well (https://github.com/mpetris/catma-core).
You can configure IvyDE to "Resolve dependencies within the workspace"

The easiest way is to use the catma6 branch, because it runs on current
MySQL or MariaDB and contains db/createCATMA6DB.sql to generate the
database structure. Make sure to fetch my latest changes.
You would need to adjust the path and db access information in the
catma.properties file. You can copy the existing one and pass in your
custom properties file with -D flag.

You need to compile the Theme and the Widgetset before the first run.
The Vaadin Plugin provides a Eclise toolbar button with two bolt nuts to
do that.

For serious setups you would need to adjust the neo4j.properties file in
the WebContent folder.

To create your own war file you can use export-to-war functionality of
Eclipse. I use Jetty as a Servlet Container but Tomcat should do as well.

Feel free to ask, if you need more assistance.

Best,

Marco

Am 28.01.2017 um 02:15 schrieb Richard Heycock:

**Comment by filterfish** [comment]
Thanks for getting back to me Marco.

So I've managed to get it compiled; as soon as I installed the Vaadin Plugin it just worked which is good.

So my next yak ( ;-) was the database, which I eventually got up and running. The problems I came across were related to: old version of `mysql-connector-java` (5.1.40 seems to work); case sensitivity (I'm deploying on Linux, I assume you are using Windows. Windows is the _only_ platform I know of which is case insensitive) and disappearing down a number of dead ends because I didn't know what I was doing.

That said I've got a local deployment running on my laptop. Yah!

So the next step how do I create an account? I see there is configuration for OAuth in the config. Do I need to set up an OAuth server? I tried to download OpenAM but although it's open source I couldn't find anywhere to download a war. Ok not to worry, I've got a local OAuth2 server so I configure that and then modify the `catma.properties` file. I restart and try to sign in (this produced `NullPointerException` in the logs) and I'm presented with a page with what appears to be different OAuth providers. I click on the: "login using the catma server" (I would go back and have a look at what the actual text is but when I refreshed the page I got an error message in the logs: `SEVERE: [{identifier=jetty}]Error opening the repository!` followed by the usual 15 million line stack trace ;-) only to be redirected to the catma OpenAM server. WTF. It turns out the catma OAuth details are hardcoded, even though they are also in `catma.properties`.

I restarted jetty so I could try and login using the Google Auth server but I only get the afore mentioned 15 million line stack trace.

I see from the code that there is a property I can set called `catma.autologin` but I can't find where I might set this. In an act of desperation I think "if I just hardcode that & move on" but on closer inspection I give and go and weep in the corner!

I also tried URLs that are typical of modern webapps such as /admin` but the main page was simply rendered (not a redirect back to `/`). Even arbitrary URLs are rendered: `http://localhost:8080/catma-6.0/rstrstrsts`!

I've started writing a comprehensive `INSTALL` document (I'll submit a PR when I finish it) but I'm completely at a loss as to how to continue. Please advise!

**Comment by mpetris** [comment]
Hi Richard,

> That said I've got a local deployment running on my laptop. Yah! 
Great :-)

> So the next step how do I create an account? I see there is
> configuration for OAuth in the config. Do I need to set up an OAuth
> server? I tried to download OpenAM but although it's open source I
> couldn't find anywhere to download a war. Ok not to worry, I've got a
> local OAuth2 server so I configure that and then modify the
> |catma.properties| file. I restart and try to sign in (this produced
> |NullPointerException| in the logs) and I'm presented with a page with
> what appears to be different OAuth providers. I click on the: "login
> using the catma server" (I would go back and have a look at what the
> actual text is but when I refreshed the page I got an error message in
> the logs: |SEVERE: [{identifier=jetty}]Error opening the repository!|
> followed by the usual 15 million line stack trace ;-) only to be
> redirected to the catma OpenAM server. WTF. It turns out the catma
> OAuth details are hardcoded, even though they are also in
> |catma.properties|.
>
I wouldn' call it exactly hardcoded, but yes it could be even more
configurable.
However OAuth isn't needed for a local setup. There is a proptery in the
properties file called RepositoryAuthenticationRequired1 which should be
set to false. Then you should not need any authentication at all, CATMA
will use the local user by default instead.
If  you really need authentication on your local machine you could
integrate your OAuth2 server by adding it the same way the other two are
integrated in the AuthenticationDialog: Add the property keys and
values, add the link button and the link button listener and it should
work. Note that even without authentication it would still be possible
to work with multiple users, by passing in the user via URL parameter.

> I see from the code that there is a property I can set called
> |catma.autologin| but I can't find where I might set this. In an act
> of desperation I think "if I just hardcode that & move on" but on
> closer inspection I give and go and weep in the corner! 
catma.autologin has a different purpose, it just takes a user to the
CATMA authentication directly.

> I also tried URLs that are typical of modern webapps such as
> /admin|but the main page was simply rendered (not a redirect back
> to|/|). Even arbitrary URLs are
> rendered:|http://localhost:8080/catma-6.0/rstrstrsts`
> <http://localhost:8080/catma-6.0/rstrstrsts%60>!
>
You should be able to access CATMA at http:localhost:8080/catma unless
you explicitly changed the document root.

> I've started writing a comprehensive |INSTALL| document (I'll submit a
> PR when I finish it) but I'm completely at a loss as to how to
> continue. Please advise!
>
Excellent!

Best,

Marco

**Comment by mpetris** [comment]
@maltem-za  kindly provided the build instructions for the [catma6 ](https://github.com/mpetris/catma/tree/catma6) branch. Thanks!

**Comment by maltem-za** [comment]
Note that the Eclipse instructions are very basic and that complete step-by-step instructions are only available for IntelliJ IDEA (see [README.md](https://github.com/mpetris/catma/blob/catma6/README.md)).

However even those are already out of date as the IntelliJ project files have since been checked in, so not all steps are required. In some cases the instructions could also do with some simplification/reordering. Having said all of that, my colleague @mbeets-afro informed me that they were still helpful in getting things up and running.
